name: Run SSH command222
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run name is ls -a vi1231
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: /home/alexmindustry/Documents/watermelonbot/watermelonbot/gitpull_restartscreen.sh; echo doneee
          host: ${{ secrets.HOST }}
          username: alexmindustry
          password: ${{ secrets.PASSWORD }}
